### ISSUE TITLE
Use `deps.yaml` to generate importmaps that will be added the root html entry

### ISSUE THREAD

**Issue by struckchure** [struckchure/gv#10]
Here is a sample file

```yaml
# deps.yaml
packages:
  - name: react
    url: https://esm.sh/react@19.1.0
  - name: react-router
    url: https://esm.sh/react-router@7.5.0
```

Should result to this

```html
<script type="importmap">
{
  "imports": {
    "react": "https://esm.sh/react@19.1.0",
    "react-router": "https://esm.sh/react-router@7.5.0"
  }
}
</script>
```

And be injected to the root html entry (`index.html`)
